### ISSUE TITLE
Carta de Correção

### ISSUE THREAD

**Issue by AllisonErd** [BLACKFISHLABS/fiscal4j#3]
Olá boa tarde. Primeiramente, parabéns pelo projeto.
Segundo, vc teria como dar um exemplo de impressão de uma carta de Correção?
Desde já agradeço. Obrigado.

**Comment by JefersonOC** [comment]
Em breve vou disponibilizar uma documentação de uso.

**Comment by AllisonErd** [comment]
Obrigado por responder @JefersonOC . Criei a minha própria e tá funcionando.
